In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
file_name1 = "games_data/lowest_rated_games.csv"
file_name2 = "games_data/top_rated_games.csv"
df = pd.concat(
    map(pd.read_csv, [file_name1, file_name2]), ignore_index=True)

In [3]:
df.drop("Unnamed: 0", axis=1, inplace=True)
df.head()

,game_name,platform,publisher,release_date,meta_scroe,user_score,develeoper,genres,num_of_players,rating,user_positive_review,user_negative_review,user_mixed_review,critic_positive_review,critic_negative_review,critic_mixed_review
0,Tharsis,PC,Choice Provisions,"Jan 11, 2016",61.0,4.8,Choice Provisions,"Miscellaneous, Board / Card Game",No Online Multiplayer,M,19,27,11.0,3.0,3.0,17.0
1,WWI Tannenberg: Eastern Front,PlayStation 4,Blackmill Games,"Jul 24, 2020",61.0,8.3,M2H,"Action, Shooter, First-Person, Tactical",Up to 40,M,4,0,2.0,3.0,1.0,6.0
2,Dungeons 2,PlayStation 4,Kalypso,"May 24, 2016",61.0,6.6,Kalypso,"Strategy, General",Up to 4,T,15,6,4.0,1.0,1.0,7.0
3,WE ARE DOOMED,PlayStation 4,Vertex Pop,"Apr 14, 2015",61.0,5.9,Vertex Pop,"Action, Shooter, Shoot-'Em-Up, Horizontal",NaN,E,10,9,3.0,2.0,1.0,6.0
4,Sixty Second Shooter Prime,Xbox One,Happion Laboratories,"Jun 18, 2014",61.0,7.1,Happion Laboratories,"Action, Shooter, Static, Shoot-'Em-Up, Top-Down",NaN,E,9,2,5.0,0.0,1.0,7.0

In [4]:

df[df["meta_scroe"].isna()]

df.dropna(subset=['meta_scroe'], inplace=True)

In [5]:
df[df['user_score'] == "tbd"]

,game_name,platform,publisher,release_date,meta_scroe,user_score,develeoper,genres,num_of_players,rating,user_positive_review,user_negative_review,user_mixed_review,critic_positive_review,critic_negative_review,critic_mixed_review
25,King Arthur,Xbox,Konami,"Nov 16, 2004",61.0,tbd,Krome Studios,"Action Adventure, Fantasy",1-2,T,0,1,1.0,2.0,2.0,11.0
30,The Messenger (2001),PC,DreamCatcher Interactive,"Feb 14, 2001",61.0,tbd,Index Multimedia,"Adventure, General, General",1 Player,T,NaN,NaN,NaN,2.0,1.0,11.0
32,Hunter's Legacy,Xbox One,Lienzo,"Jan 20, 2017",61.0,tbd,Lienzo,"Action, Action Adventure, Platformer, Open-Wor...",No Online Multiplayer,E,0,0,1.0,1.0,1.0,5.0
38,Nikoli's Pencil Puzzle,3DS,Konami,"Oct 25, 2011",61.0,tbd,NATSUME ATARI Inc.,"Miscellaneous, Puzzle, Puzzle, Puzzle, Logic, ...",NaN,E,2,1,0.0,1.0,0.0,6.0
41,Maglam Lord,PlayStation 4,PQube,"Feb 4, 2022",61.0,tbd,Felistella,"Role-Playing, Action RPG",No Online Multiplayer,T,NaN,NaN,NaN,0.0,0.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7845,Fly Together!,Switch,Northplay ApS,"Apr 29, 2021",81.0,tbd,Northplay ApS,"Strategy, Management, Business / Tycoon",No Online Multiplayer,NaN,1,0,1,6.0,0.0,2.0
7896,Overboard!,PC,inkle,"Jun 2, 2021",81.0,tbd,inkle,"Adventure, General",No Online Multiplayer,NaN,1,0,2,7.0,0.0,1.0
7897,Silicon Dreams,PC,Clockwork Bird,"Apr 20, 2021",81.0,tbd,Clockwork Bird,"Action, General, Adventure, 3D, First-Person",No Online Multiplayer,NaN,0,0,3,6.0,0.0,1.0
7971,Tiger Woods PGA Tour 07,PlayStation 3,EA Sports,"Nov 14, 2006",81.0,tbd,EA Redwood Shores,"Sports, Traditional, Individual, Golf, Sim, Sim",Up to 4,E,1,1,1,27.0,0.0,3.0
7984,FORM,PC,Charm Games,"Jun 1, 2017",81.0,tbd,Charm Games,"Adventure, General, 3D, First-Person",No Online Multiplayer,NaN,0,1,1,7.0,0.0,0.0

In [6]:
df.replace("tbd", np.nan, inplace=True)
df[df["user_score"] == "tbd"]

Empty DataFrame
Columns: [game_name, platform, publisher, release_date, meta_scroe, user_score, develeoper, genres, num_of_players, rating, user_positive_review, user_negative_review, user_mixed_review, critic_positive_review, critic_negative_review, critic_mixed_review]
Index: []

In [7]:
df.user_score = df.user_score.astype("float")

In [8]:
df["user_score"].fillna(df["user_score"].mean(), inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7994 entries, 0 to 7997
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_name               7994 non-null   object
 1   platform                7994 non-null   object
 2   publisher               7989 non-null   object
 3   release_date            7994 non-null   object
 4   meta_scroe              7994 non-null   float64
 5   user_score              7994 non-null   float64
 6   develeoper              7983 non-null   object
 7   genres                  7994 non-null   object
 8   num_of_players          6489 non-null   object
 9   rating                  7352 non-null   object
 10  user_positive_review    7512 non-null   object
 11  user_negative_review    7512 non-null   object
 12  user_mixed_review       7512 non-null   object
 13  critic_positive_review  7994 non-null   float64
 14  critic_negative_review  7994 non-null   float64
 15  critic_mixed_review     7994 non-null   float64
dtypes: float64(5), object(11)
memory usage: 1.0+ MB

In [10]:
# הנתונים בעלי המיספרים הגדולים עם פסיקים במיספרים
# ולכן עמרה פשוטה לסוג אינט לא תעזור פה
df["user_positive_review"][6000]

'1,293'

In [11]:
# עמרה של כל הנתוני review
# בעלי המיספרים הגבועים
colums = ["user_positive_review", "user_negative_review", "user_mixed_review"]
for column in colums:
    nums = []
    for string in df[column]:
        if(type(string) != float):
            nums.append(int(string.replace(",", "")))
        else:
            nums.append(np.nan)
    df[column] = nums
    #games_data[column] = games_data[column].astype('int')

df.iloc[:,11:14]

      user_negative_review  user_mixed_review  critic_positive_review
0                     27.0                NaN                     3.0
1                      0.0                NaN                     3.0
2                      6.0                NaN                     1.0
3                      9.0                NaN                     2.0
4                      2.0                NaN                     0.0
...                    ...                ...                     ...
7993                   5.0                6.0                    20.0
7994                  10.0                9.0                    32.0
7995                 536.0              613.0                    53.0
7996                   2.0                1.0                    10.0
7997                  10.0               12.0                     7.0

[7994 rows x 3 columns]

In [12]:
columns = [
    "user_positive_review", "user_negative_review", "user_mixed_review",
    "critic_positive_review", "critic_negative_review", "critic_mixed_review"
]
for column in columns:
    df[column] = df[column].astype("float")
    df[column].fillna(df[column].mean(), inplace=True)

In [13]:
df[df["user_negative_review"].isna()]

Empty DataFrame
Columns: [game_name, platform, publisher, release_date, meta_scroe, user_score, develeoper, genres, num_of_players, rating, user_positive_review, user_negative_review, user_mixed_review, critic_positive_review, critic_negative_review, critic_mixed_review]
Index: []

In [14]:
# making a new normalize column of 'user_positive_review'
user_review = df.iloc[:,10:13].copy()
user_review_sum = user_review["user_positive_review"] + user_review["user_negative_review"] + user_review["user_mixed_review"]
user_review["user_positive_normalize"] = user_review["user_positive_review"] / user_review_sum

df["user_positive_normelize"] = user_review["user_positive_normalize"]

In [15]:
# making a new normalize column of 'critic_positive_review'
critic_review = df.iloc[:,-4:-1].copy()
critic_review_sum = critic_review["critic_positive_review"] + critic_review["critic_mixed_review"] + critic_review["critic_negative_review"]
critic_review["critic_positive_normalize"] = critic_review["critic_positive_review"] / critic_review_sum

df["critic_positive_normelize"] = critic_review["critic_positive_normalize"]

In [16]:
df.drop(columns, axis=1, inplace=True)
df.head()

,game_name,platform,publisher,release_date,meta_scroe,user_score,develeoper,genres,num_of_players,rating,user_positive_normelize,critic_positive_normelize
0,Tharsis,PC,Choice Provisions,"Jan 11, 2016",61.0,4.8,Choice Provisions,"Miscellaneous, Board / Card Game",No Online Multiplayer,M,0.177295,0.130435
1,WWI Tannenberg: Eastern Front,PlayStation 4,Blackmill Games,"Jul 24, 2020",61.0,8.3,M2H,"Action, Shooter, First-Person, Tactical",Up to 40,M,0.061382,0.300000
2,Dungeons 2,PlayStation 4,Kalypso,"May 24, 2016",61.0,6.6,Kalypso,"Strategy, General",Up to 4,T,0.182557,0.111111
3,WE ARE DOOMED,PlayStation 4,Vertex Pop,"Apr 14, 2015",61.0,5.9,Vertex Pop,"Action, Shooter, Shoot-'Em-Up, Horizontal",NaN,E,0.124741,0.222222
4,Sixty Second Shooter Prime,Xbox One,Happion Laboratories,"Jun 18, 2014",61.0,7.1,Happion Laboratories,"Action, Shooter, Static, Shoot-'Em-Up, Top-Down",NaN,E,0.124712,0.000000

In [17]:
import re

In [18]:
num_of_players_unique = list(df["num_of_players"].unique())

replace_map_for_max_players = {}
replace_map_for_online_game = {}

for val in num_of_players_unique:
    if(type(val) != float):
        max_player_list = [int(s) for s in re.findall(r'\b\d+\b', val)]
        if(max_player_list):
            max_player = max(max_player_list)
        else:
            max_player = np.nan
        replace_map_for_max_players[val] = max_player

        
        online = ('Online' in val) and ('No Online' not in val)
        if(max_player != np.nan):
            if(max_player >= 4):
                online = True
        
        replace_map_for_online_game[val] = online

    else:
        replace_map_for_max_players[val] = np.nan
        replace_map_for_online_game[val] = np.nan
            
df["max_players"] = df["num_of_players"].copy()
df["online_game"] = df["num_of_players"].copy()

df["max_players"].replace(replace_map_for_max_players, inplace=True)
df["online_game"].replace(replace_map_for_online_game, inplace=True)

In [19]:
df["online_game"].unique()

array([False, True, nan], dtype=object)

In [20]:
df = pd.get_dummies(df, columns=["online_game"], prefix=["online_game"], dummy_na=True)

In [21]:
df.drop("num_of_players", axis=1, inplace=True)

In [22]:
df.head()

,game_name,platform,publisher,release_date,meta_scroe,user_score,develeoper,genres,rating,user_positive_normelize,critic_positive_normelize,max_players,online_game_False,online_game_True,online_game_nan
0,Tharsis,PC,Choice Provisions,"Jan 11, 2016",61.0,4.8,Choice Provisions,"Miscellaneous, Board / Card Game",M,0.177295,0.130435,NaN,1,0,0
1,WWI Tannenberg: Eastern Front,PlayStation 4,Blackmill Games,"Jul 24, 2020",61.0,8.3,M2H,"Action, Shooter, First-Person, Tactical",M,0.061382,0.300000,40.0,0,1,0
2,Dungeons 2,PlayStation 4,Kalypso,"May 24, 2016",61.0,6.6,Kalypso,"Strategy, General",T,0.182557,0.111111,4.0,0,1,0
3,WE ARE DOOMED,PlayStation 4,Vertex Pop,"Apr 14, 2015",61.0,5.9,Vertex Pop,"Action, Shooter, Shoot-'Em-Up, Horizontal",E,0.124741,0.222222,NaN,0,0,1
4,Sixty Second Shooter Prime,Xbox One,Happion Laboratories,"Jun 18, 2014",61.0,7.1,Happion Laboratories,"Action, Shooter, Static, Shoot-'Em-Up, Top-Down",E,0.124712,0.000000,NaN,0,0,1

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7994 entries, 0 to 7997
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   game_name                  7994 non-null   object
 1   platform                   7994 non-null   object
 2   publisher                  7989 non-null   object
 3   release_date               7994 non-null   object
 4   meta_scroe                 7994 non-null   float64
 5   user_score                 7994 non-null   float64
 6   develeoper                 7983 non-null   object
 7   genres                     7994 non-null   object
 8   rating                     7352 non-null   object
 9   user_positive_normelize    7994 non-null   float64
 10  critic_positive_normelize  7994 non-null   float64
 11  max_players                3833 non-null   float64
 12  online_game_False          7994 non-null   uint8
 13  online_game_True           7994 non-null   uint8
 14  online_game_nan            7994 non-null   uint8
dtypes: float64(5), object(7), uint8(3)
memory usage: 1.1+ MB

In [24]:
# develeoper
# publisher
# rating
# release_date
# platform
# genres

In [25]:
df["max_players"].unique() # אולי צריך להפוך את זה לסטרינג (משתנה בדיד)

array([nan, 40.,  4.,  2.,  3.,  1., 12.,  8.,  6.,  5., 10., 16., 64.,
       32., 44.,  9., 24., 20., 60., 30., 14., 22., 18., 15.])

In [26]:
df["platform"].unique() # נשנה את השמות שלא יהיו עם מספרים

array(['PC', 'PlayStation 4', 'Xbox One', 'PSP', '3DS', 'Switch',
       'Xbox 360', 'PlayStation 2', 'PlayStation 3', 'DS', 'Xbox',
       'Game Boy Advance', 'PlayStation', 'PlayStation Vita', 'Dreamcast',
       'PlayStation 5', 'GameCube', 'Wii U', 'Xbox Series X', 'Wii',
       'Nintendo 64', 'Stadia'], dtype=object)

In [27]:
df["rating"].unique() # אולי נמספר- נבדוק מה כל דירוג כזה אומר, וניקבע לפי זה אולי מיספור עם סדר מסויים

array(['M', 'T', 'E', 'E10+', nan, 'RP', 'AO', 'K-A'], dtype=object)

In [28]:
df["release_date"].unique() # נפריד ל3 עמודות - שנה, יום, חודש (או רק 2 חודש ושנה)

array(['Jan 11, 2016', 'Jul 24, 2020', 'May 24, 2016', ...,
       'Mar 27, 2013', 'Sep  7, 2016', 'Mar 14, 2019'], dtype=object)

In [48]:
print(re.findall(r'\b\d+\b', 'Sep  7, 2016')) # איך למצוא את היום והשנה
print(re.findall(r'(\w\w\w) ', 'Sep  7, 2016')) # איך למצוא את החודש

['7', '2016']
['Sep']

In [29]:
# צריך לבדוק אם אפשר להשאיר ככה, איך הלמידת מכונה תוכל ערכים כאלו
len(df["publisher"].unique()) # כניראה נשאיר ככה?

1082

In [30]:
len(df["develeoper"].unique()) # כניראה נשאיר ככה?

2248

In [31]:
df["genres"] # נפריד לכמה עמודות של ג'נרים

0                        Miscellaneous, Board / Card Game
1                 Action, Shooter, First-Person, Tactical
2                                       Strategy, General
3               Action, Shooter, Shoot-'Em-Up, Horizontal
4         Action, Shooter, Static, Shoot-'Em-Up, Top-Down
                              ...
7993    Strategy, Real-Time, General, General, Fantasy...
7994             Strategy, Turn-Based, Real-Time, Tactics
7995    Miscellaneous, Action Adventure, Edutainment, ...
7996                       Puzzle, Action, Platformer, 3D
7997          Action, Miscellaneous, Rhythm, Music, Music
Name: genres, Length: 7994, dtype: object

In [32]:
genres_names = set()
for genre in df["genres"]:
    genre_list = genre.split(", ")
    for name in genre_list:
        if(name):
            genres_names.add(name)
print(len(genres_names))

166

In [33]:
genres_names # כל הג'נרים שקיימים

{'2D',
 '3D',
 '4X',
 'Action',
 'Action Adventure',
 'Action RPG',
 'Adventure',
 'Alternative',
 'Application',
 'Arcade',
 'Artillery',
 'Athletics',
 'Automobile',
 'Baseball',
 'Basketball',
 "Beat-'Em-Up",
 'Biking',
 'Billiards',
 'Board / Card Game',
 'Board Games',
 'Bowling',
 'Boxing',
 'Boxing / Martial Arts',
 'Breeding/Constructing',
 'Business / Tycoon',
 'Car Combat',
 'Card Battle',
 'Career',
 'City Building',
 'Civilian',
 'Civilian Plane',
 'Combat',
 'Command',
 'Compilation',
 'Console-style RPG',
 'Dancing',
 'Defense',
 'Demolition Derby',
 'Driving',
 'Edutainment',
 'Exercise / Fitness',
 'Fantasy',
 'Fighting',
 'First-Person',
 'Fishing',
 'Flight',
 'Football',
 'Formula One',
 'Futuristic',
 'Futuristic Jet',
 'Futuristic Sub',
 'GT / Street',
 'Gambling',
 'General',
 'Golf',
 'Government',
 'Helicopter',
 'Hidden Object',
 'Historic',
 'Horizontal',
 'Horror',
 'Horse Racing',
 'Hunting',
 'Ice Hockey',
 'Individual',
 'Interactive Movie',
 'Japanese-Style',
 'Kart',
 'Large Spaceship',
 'Light Gun',
 'Linear',
 'Logic',
 'MOBA',
 'Management',
 'Marine',
 'Massively Multiplayer',
 'Massively Multiplayer Online',
 'Matching',
 'Mech',
 'Metroidvania',
 'Military',
 'Miscellaneous',
 'Mission-based',
 'Modern',
 'Modern Jet',
 'Motocross',
 'Motorcycle',
 'Music',
 'Music Maker',
 'Nature',
 'Olympic Sports',
 'On-foot',
 'Open-World',
 'Other',
 'PC-style RPG',
 'Parlor',
 'Party',
 'Party / Minigame',
 'Pet',
 'Pinball',
 'Platformer',
 'Point-and-Click',
 'Puzzle',
 'Racing',
 'Rail',
 'Rally / Offroad',
 'Real-Time',
 'Rhythm',
 'Roguelike',
 'Role-Playing',
 'Rugby',
 'Sandbox',
 'Sci-Fi',
 'Scrolling',
 'Ship',
 "Shoot-'Em-Up",
 'Shooter',
 'Sim',
 'Simulation',
 'Skate / Skateboard',
 'Skateboarding',
 'Skating',
 'Ski / Snowboard',
 'Skiing',
 'Small Spaceship',
 'Snow / Water',
 'Snowboarding',
 'Soccer',
 'Space',
 'Sports',
 'Stacking',
 'Static',
 'Stock Car',
 'Strategy',
 'Street',
 'Submarine',
 'Surf / Wakeboard',
 'Surfing',
 'Survival',
 'Tactical',
 'Tactics',
 'Tank',
 'Team',
 'Tennis',
 'Text',
 'Third-Person',
 'Top-Down',
 'Traditional',
 'Train',
 'Trainer',
 'Trivia / Game Show',
 'Truck',
 'Turn-Based',
 'Tycoon',
 'Vehicle',
 'Vertical',
 'Videos',
 'Virtual',
 'Virtual Life',
 'Visual Novel',
 'Volleyball',
 'WWII',
 'Wakeboarding',
 'Wargame',
 'Western-Style',
 'Wrestling'}

In [34]:
# חוץ מזה צריך לנרמל את 
# meta_scroe
# user_score